name: test-publish-to-pypi

on:
  push:
    tags:
      - 'test*'

jobs:
  build-release:
    name: Build release wheel
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_24_x86_64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build a wheel and source tarball
        env:
          Python3_ROOT_DIR: /opt/python/cp39-cp39
        run: >-
          /opt/python/cp39-cp39/bin/python -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Audit resulting wheel into Manylinux
        run: auditwheel repair dist/*.whl -w dist/
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/*manylinux*.whl
            dist/*.tar.gz
  publish-test:
    name: Publish to TestPyPI
    needs: build-release
    runs-on: ubuntu-latest
    environment: TestPyPI
    steps:
      - name: Retrieve built archive
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
